# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: txf_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'txf_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etxf_data.proto\x12\x03txf\"\x8c\x01\n\x04Tick\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\x12\r\n\x05\x63lose\x18\x03 \x01(\x03\x12\x0e\n\x06volume\x18\x04 \x01(\x05\x12\x11\n\ttick_type\x18\x05 \x01(\x05\x12\x18\n\x10underlying_price\x18\x06 \x01(\x03\x12\x14\n\x0ctotal_volume\x18\x07 \x01(\x05\"\xd4\x01\n\x06\x42idAsk\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\x12\x15\n\rbid_total_vol\x18\x03 \x01(\x05\x12\x15\n\rask_total_vol\x18\x04 \x01(\x05\x12\x11\n\tbid_price\x18\x05 \x03(\x03\x12\x12\n\nbid_volume\x18\x06 \x03(\x05\x12\x14\n\x0c\x64iff_bid_vol\x18\x07 \x03(\x05\x12\x11\n\task_price\x18\x08 \x03(\x03\x12\x12\n\nask_volume\x18\t \x03(\x05\x12\x14\n\x0c\x64iff_ask_vol\x18\n \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'txf_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICK']._serialized_start=24
  _globals['_TICK']._serialized_end=164
  _globals['_BIDASK']._serialized_start=167
  _globals['_BIDASK']._serialized_end=379
# @@protoc_insertion_point(module_scope)
